openapi: 3.0.3
info:
  title: Music info
  version: 0.0.1
servers:
- url: /
paths:
  /info:
    get:
      parameters:
      - name: group
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: song
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetail'
        "400":
          description: Bad request
        "500":
          description: Internal server error
components:
  schemas:
    SongDetail:
      required:
      - link
      - releaseDate
      - text
      type: object
      properties:
        releaseDate:
          type: string
          example: 16.07.2006
        text:
          type: string
          example: "Ooh baby, don't you know I suffer? Ooh baby, can you hear me
            moan? You caught me under false pretensesHow long before you let
            me go? Ooh You set my soul alight Ooh You set my soul alight"
        link:
          type: string
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
      example:
        releaseDate: 16.07.2006
        link: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        text: "Ooh baby, don't you know I suffer? Ooh baby, can you hear me moan?
          You caught me under false pretenses How long before you let me go?
          Ooh You set my soul alight Ooh You set my soul alight"
